language: java
jdk:
  - openjdk8

branches:
  only:
    - master


# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'france1988@naver.com'


before_deploy:
  - zip -r lombre-springboot-webservice *
  - mkdir -p deploy
  - mv lombre-springboot-webservice.zip deploy/lombre-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: lombre-springboot-build # S3 버킷 명
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로...
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: lombre-springboot-build # S3 버킷 명
    key: lombre-springboot-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: lombre-springboot-webservice # CodeDeploy 웹에서 등록한 애플리케이션 명
    deployment_group: lombre-springboot-webservice-group # CodeDeploy 웹에서 등록한 배포 그룹 명
    region: ap-northeast-2
    wait-until-deployed: true